class HomeScreenConstants {
  static const Map<String, String> categoryImageMap = {
    'beauty': 'assets/category-list/beauty.jpg',
    'fragrances': 'assets/category-list/fragrances.jpg',
    'furniture': 'assets/category-list/furniture.jpg',
    'groceries': 'assets/category-list/groceries.jpg',
    'home-decoration': 'assets/category-list/home-decoration.jpg',
    'kitchen-accessories': 'assets/category-list/kitchen-accessories.jpg',
    'laptops': 'assets/category-list/laptops.jpg',
    'mens-shirts': 'assets/category-list/mens-shirts.jpg',
    'mens-shoes': 'assets/category-list/mens-shoes.jpg',
    'mens-watches': 'assets/category-list/mens-watches.jpg',
    'mobile-accessories': 'assets/category-list/mobile-accessories.jpg',
    'motorcycle': 'assets/category-list/motorcycle.jpg',
    'skin-care': 'assets/category-list/skin-care.jpg',
    'smartphones': 'assets/category-list/smartphones.jpg',
    'sports-accessories': 'assets/category-list/sports-accessories.jpg',
    'sunglasses': 'assets/category-list/sunglasses.jpg',
    'tablets': 'assets/category-list/tablets.jpg',
    'tops': 'assets/category-list/tops.jpg',
    'vehicle': 'assets/category-list/vehicle.jpg',
    'womens-bags': 'assets/category-list/womens-bags.jpg',
    'womens-dresses': 'assets/category-list/womens-dresses.jpg',
    'womens-jewellery': 'assets/category-list/womens-jewellery.jpg',
    'womens-shoes': 'assets/category-list/womens-shoes.jpg',
    'womens-watches': 'assets/category-list/womens-watches.jpg',
  };

  static const List<String> categoryList = [
    'beauty',
    'fragrances',
    'furniture',
    'groceries',
    'home-decoration',
    'kitchen-accessories',
    'laptops',
    'mens-shirts',
    'mens-shoes',
    'mens-watches',
    'mobile-accessories',
    'motorcycle',
    'skin-care',
    'smartphones',
    'sports-accessories',
    'sunglasses',
    'tablets',
    'tops',
    'vehicle',
    'womens-bags',
    'womens-dresses',
    'womens-jewellery',
    'womens-shoes',
    'womens-watches',
  ];
}
